apiVersion: v1
kind: ServiceAccount
metadata:
  name: aks-jobscheduler
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: aks-jobscheduler-secret
  annotations: 
    kubernetes.io/service-account.name: aks-jobscheduler
type: kubernetes.io/service-account-token
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: jobs-manager
rules:
- apiGroups: ["batch", "extensions"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jobs-manager-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jobs-manager
subjects:
- kind: ServiceAccount
  name: aks-jobscheduler
  namespace: default